# Site settings
title_left    : "robert"
title_right   : "g" # default: ""
description   : "robert głód blog"
keywords      : ""
url           : "https://robg.netlify.com"
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-125799130-1
twitter_username  : ""
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "rglod"
postshare_enabled : false

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "rg"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jekyll-admin

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
